/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/header-footer/AppFooter.vue')['default']
    AppFooterProfile: typeof import('./src/components/header-footer/AppFooterProfile.vue')['default']
    AppHeader: typeof import('./src/components/header-footer/AppHeader.vue')['default']
    AppNotFound: typeof import('./src/components/ui/AppNotFound.vue')['default']
    AppTitle: typeof import('./src/components/ui/AppTitle.vue')['default']
    CButton: typeof import('./src/components/ui/CButton.vue')['default']
    CDatepicker: typeof import('./src/components/ui/CDatepicker.vue')['default']
    CFIleSelect: typeof import('./src/components/ui/CFIleSelect.vue')['default']
    CInput: typeof import('./src/components/ui/CInput.vue')['default']
    CLoader: typeof import('./src/components/ui/CLoader.vue')['default']
    CModal: typeof import('./src/components/ui/CModal.vue')['default']
    CStatus: typeof import('./src/components/main/CStatus.vue')['default']
    DropFile: typeof import('./src/components/ui/DropFile.vue')['default']
    Editor: typeof import('./src/components/main/Editor.vue')['default']
    FileShow: typeof import('./src/components/main/FileShow.vue')['default']
    FroalaEditor: typeof import('./src/components/main/FroalaEditor.vue')['default']
    GenerateProtocol: typeof import('./src/components/generate/GenerateProtocol.vue')['default']
    ProfileMenu: typeof import('./src/components/header-footer/ProfileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectDistrict: typeof import('./src/components/ui/SelectDistrict.vue')['default']
    SelectPrice: typeof import('./src/components/ui/SelectPrice.vue')['default']
    SelectRegion: typeof import('./src/components/ui/SelectRegion.vue')['default']
    Signature: typeof import('./src/components/main/Signature.vue')['default']
    ViewDoc: typeof import('./src/components/main/ViewDoc.vue')['default']
  }
}
