/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//category': RouteRecordInfo<'//category', '/category', Record<never, never>, Record<never, never>>,
    '//criterion': RouteRecordInfo<'//criterion', '/criterion', Record<never, never>, Record<never, never>>,
    '//dashboard': RouteRecordInfo<'//dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    '//organization/': RouteRecordInfo<'//organization/', '/organization', Record<never, never>, Record<never, never>>,
    '//organization/[id]': RouteRecordInfo<'//organization/[id]', '/organization/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//organization/[id]/check': RouteRecordInfo<'//organization/[id]/check', '/organization/:id/check', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//organization/[id]/detail': RouteRecordInfo<'//organization/[id]/detail', '/organization/:id/detail', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//organization/[id]/rate': RouteRecordInfo<'//organization/[id]/rate', '/organization/:id/rate', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//organization/[id]/rate-history': RouteRecordInfo<'//organization/[id]/rate-history', '/organization/:id/rate-history', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//organization/add': RouteRecordInfo<'//organization/add', '/organization/add', Record<never, never>, Record<never, never>>,
    '//organization/update': RouteRecordInfo<'//organization/update', '/organization/update', Record<never, never>, Record<never, never>>,
    '//settings': RouteRecordInfo<'//settings', '/settings', Record<never, never>, Record<never, never>>,
    '//user': RouteRecordInfo<'//user', '/user', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/login copy': RouteRecordInfo<'/auth/login copy', '/auth/login copy', Record<never, never>, Record<never, never>>,
  }
}
