// src/router.ts
import { createRouter, createWebHistory } from 'vue-router'
import { routes } from 'vue-router/auto-routes'// Import routes generated by unplugin-vue-router
import { useAuthStore } from './store/auth'

const router = createRouter({
  history: createWebHistory(),
  routes,
})

const isAuthenticated = useStorage('access_token', '')
router.beforeEach((to, from, next) => {

  if (!to.fullPath.startsWith('/auth') && !isAuthenticated.value) {
    return next('/auth/login')
  }
  else {
    const roles = to.meta.roles || [] as any
    const { user } = useAuthStore()
    if (roles.length && !roles.includes(user?.role)) {
      return next('/dashboard')
    }
    return next()
  }
  return next()
}
)

export default router