// src/router.ts
import { createRouter, createWebHistory } from 'vue-router'
import { routes } from 'vue-router/auto-routes'// Import routes generated by unplugin-vue-router

const router = createRouter({
  history: createWebHistory(),
  routes,
})

const isAuthenticated = useStorage('access_token', '')
router.beforeEach((to, from, next) => {
  if (!to.fullPath.startsWith('/auth') && !isAuthenticated.value) {
    return next('/auth/login')
  }
  else {
    return next()
  }
  return next()
}
)

export default router